import { del, get, post, put, upload } from '@/utils/request'
export const getImSessions = (params?: any) => get<any>('/im/sessions', params)
export const getImMessages = (sessionId: number) => get<any>(`/im/sessions/${sessionId}/messages`)
export const sendImMessage = (sessionId: number, content: string) => post<any>(`/im/sessions/${sessionId}/messages`, { content, sender_type: 'staff' })
export const replyImSession = (sessionId: number, payload: any) => post<any>(`/im/sessions/${sessionId}/reply`, payload)
export const uploadImAttachment = (sessionId: number, filePath: string) => upload<any>('/im/upload', filePath, 'file', { session_id: String(sessionId) })
export const getAutoReplies = () => get<any>('/im/auto-replies')
export const createAutoReply = (payload: any) => post<any>('/im/auto-replies', payload)
export const updateAutoReply = (id: number, payload: any) => put<any>(`/im/auto-replies/${id}`, payload)
export const deleteAutoReply = (id: number) => del<any>(`/im/auto-replies/${id}`)
export const getStaffStatus = () => get<any>('/im/staff/status')
export const setStaffOnline = (payload: { online: boolean }) => post<any>('/im/staff/online', payload)
export const acceptSession = (sessionId: number) => post<any>(`/im/sessions/${sessionId}/accept`)
export const closeSession = (sessionId: number) => post<any>(`/im/sessions/${sessionId}/close`)
export const transferSession = (sessionId: number, payload: { to_staff_id: number; remark?: string }) => post<any>(`/im/sessions/${sessionId}/transfer`, payload)
